Q. 19 (a)

In [1]:
import numpy as np

# Define the matrix A
A = np.array([[2, 1],
              [1, 0]])

# Compute the SVD
U, S, Vt = np.linalg.svd(A)

# Construct the Sigma matrix
Sigma = np.diag(S)

# Reconstruct A from the SVD components
reconstructed_A = np.dot(U, np.dot(Sigma, Vt))

# Display the results
print("Original Matrix A:")
print(A)

print("\nSingular Value Decomposition:")
print("U:")
print(U)
print("\nSigma:")
print(Sigma)
print("\nVt:")
print(Vt)

print("\nReconstructed Matrix A:")
print(reconstructed_A)


Original Matrix A:
[[2 1]
 [1 0]]

Singular Value Decomposition:
U:
[[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]]

Sigma:
[[2.41421356 0.        ]
 [0.         0.41421356]]

Vt:
[[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]

Reconstructed Matrix A:
[[2.00000000e+00 1.00000000e+00]
 [1.00000000e+00 4.38470705e-18]]


(b)

In [2]:
import numpy as np

# Define the matrix A
A = np.array([[2, 1],
              [1, 0],
              [0, 1]])

# Compute the SVD
U, S, Vt = np.linalg.svd(A)

# Construct the Sigma matrix
Sigma = np.zeros_like(A, dtype=float)
Sigma[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(S)

# Reconstruct A from the SVD components
reconstructed_A = np.dot(U, np.dot(Sigma, Vt))

# Display the results
print("Original Matrix A:")
print(A)

print("\nSingular Value Decomposition:")
print("U:")
print(U)
print("\nSigma:")
print(Sigma)
print("\nVt:")
print(Vt)

print("\nReconstructed Matrix A:")
print(reconstructed_A)


Original Matrix A:
[[2 1]
 [1 0]
 [0 1]]

Singular Value Decomposition:
U:
[[-9.12870929e-01  4.80183453e-17 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01  8.16496581e-01]
 [-1.82574186e-01  8.94427191e-01  4.08248290e-01]]

Sigma:
[[2.44948974 0.        ]
 [0.         1.        ]
 [0.         0.        ]]

Vt:
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]

Reconstructed Matrix A:
[[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -1.25949234e-17]
 [-1.79128377e-16  1.00000000e+00]]


(c)

In [3]:
import numpy as np

# Define the matrix A
A = np.array([[2, 1],
              [-1, 1],
              [1, 1],
              [2, -1]])

# Compute the SVD
U, S, Vt = np.linalg.svd(A)

# Construct the Sigma matrix
Sigma = np.zeros_like(A, dtype=float)
Sigma[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(S)

# Reconstruct A from the SVD components
reconstructed_A = np.dot(U, np.dot(Sigma, Vt))

# Display the results
print("Original Matrix A:")
print(A)

print("\nSingular Value Decomposition:")
print("U:")
print(U)
print("\nSigma:")
print(Sigma)
print("\nVt:")
print(Vt)

print("\nReconstructed Matrix A:")
print(reconstructed_A)


Original Matrix A:
[[ 2  1]
 [-1  1]
 [ 1  1]
 [ 2 -1]]

Singular Value Decomposition:
U:
[[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]]

Sigma:
[[3.16227766 0.        ]
 [0.         2.        ]
 [0.         0.        ]
 [0.         0.        ]]

Vt:
[[-1. -0.]
 [-0. -1.]]

Reconstructed Matrix A:
[[ 2.  1.]
 [-1.  1.]
 [ 1.  1.]
 [ 2. -1.]]


(d)

In [4]:
import numpy as np

# Define the matrix A
A = np.array([[1, 1, 0],
              [-1, 0, 1],
              [0, 1, -1],
              [1, 1, -1]])

# Compute the SVD
U, S, Vt = np.linalg.svd(A)

# Construct the Sigma matrix
Sigma = np.zeros_like(A, dtype=float)
Sigma[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(S)

# Reconstruct A from the SVD components
reconstructed_A = np.dot(U, np.dot(Sigma, Vt))

# Display the results
print("Original Matrix A:")
print(A)

print("\nSingular Value Decomposition:")
print("U:")
print(U)
print("\nSigma:")
print(Sigma)
print("\nVt:")
print(Vt)

print("\nReconstructed Matrix A:")
print(reconstructed_A)


Original Matrix A:
[[ 1  1  0]
 [-1  0  1]
 [ 0  1 -1]
 [ 1  1 -1]]

Singular Value Decomposition:
U:
[[-4.36435780e-01  7.07106781e-01  4.08248290e-01 -3.77964473e-01]
 [ 4.36435780e-01  7.07106781e-01 -4.08248290e-01  3.77964473e-01]
 [-4.36435780e-01  3.33066907e-16 -8.16496581e-01 -3.77964473e-01]
 [-6.54653671e-01  3.33066907e-16 -5.55111512e-17  7.55928946e-01]]

Sigma:
[[2.64575131 0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]]

Vt:
[[-0.57735027 -0.57735027  0.57735027]
 [ 0.          0.70710678  0.70710678]
 [ 0.81649658 -0.40824829  0.40824829]]

Reconstructed Matrix A:
[[ 1.00000000e+00  1.00000000e+00  2.52368982e-17]
 [-1.00000000e+00 -9.82612508e-17  1.00000000e+00]
 [ 3.04476818e-17  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -1.00000000e+00]]


(e)

In [7]:
import numpy as np
import time

# Define the matrix A
A = np.array([[0, 1, 1],
              [0, 1, 0],
              [1, 1, 0],
              [0, 1, 0],
              [1, 0, 1]])

start_time = time.time()

# Compute the SVD
U, S, Vt = np.linalg.svd(A)

end_time = time.time()

elapsed_time = end_time - start_time

# Construct the Sigma matrix
Sigma = np.zeros_like(A, dtype=float)
Sigma[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(S)

# Reconstruct A from the SVD components
reconstructed_A = np.dot(U, np.dot(Sigma, Vt))

# Display the results
print("Original Matrix A:")
print(A)

print("\nSingular Value Decomposition:")
print("U:")
print(U)
print("\nSigma:")
print(Sigma)
print("\nVt:")
print(Vt)

print("\nReconstructed Matrix A:")
print(reconstructed_A)


print(elapsed_time)


Original Matrix A:
[[0 1 1]
 [0 1 0]
 [1 1 0]
 [0 1 0]
 [1 0 1]]

Singular Value Decomposition:
U:
[[-5.47722558e-01 -4.11856119e-16  7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01  4.08248290e-01  1.60009123e-16 -5.43516408e-01
   6.36073827e-01]
 [-5.47722558e-01  1.63994382e-16 -7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01  4.08248290e-01  2.13371358e-16  8.07633333e-01
   2.18468301e-01]
 [-3.65148372e-01 -8.16496581e-01 -9.35206447e-17  1.32058463e-01
   4.27271064e-01]]

Sigma:
[[2.23606798 0.         0.        ]
 [0.         1.41421356 0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]

Vt:
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-5.77350269e-01  5.77350269e-01 -5.77350269e-01]
 [-7.07106781e-01  3.33066907e-16  7.07106781e-01]]

Reconstructed Matrix A:
[[-8.18273505e-17  1.00000000e+00  1.00000000e+00]
 [-1.63617332e-16  1.00000000e+00 -6.78319155e-16]
